#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENV_PATH = join(ROOT, '.env');
const OUT_PATH = join(ROOT, 'src', 'features', 'ai', 'env.generated.ts');

function parseEnv(src) {
  const out = {};
  for (const rawLine of src.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

let env = {};
try {
  env = parseEnv(readFileSync(ENV_PATH, 'utf8'));
} catch {
  env = {};
}

const apiKey = env.MISTRAL_API_KEY ?? '';
const model = env.MISTRAL_MODEL ?? 'mistral-small-latest';
const baseUrl = env.MISTRAL_API_BASE_URL ?? 'https://api.mistral.ai';

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(
  OUT_PATH,
  [
    '/* Auto-generated by scripts/generate-env.mjs. Do not commit. */',
    `export const MISTRAL_API_KEY = ${JSON.stringify(apiKey)};`,
    `export const MISTRAL_MODEL = ${JSON.stringify(model)};`,
    `export const MISTRAL_API_BASE_URL = ${JSON.stringify(baseUrl)};`,
    '',
  ].join('\n'),
  'utf8',
);

if (!apiKey) {
  console.warn('[generate-env] MISTRAL_API_KEY is empty; the app will show the API as unavailable.');
} else {
  console.log('[generate-env] Mistral env generated.');
}
