#!/usr/bin/env node
/**
 * Clean the project build + download artefacts.
 *
 * Removes, in order of "expensive to re-create":
 *   - dist/                      built extension + bundled TS (npm run build:all)
 *   - dist-extension-types/      emitted type declarations (legacy target)
 *   - scripts/model-lock.json    reproducible model download lock (gitignored)
 *   - *.log                      stray logs (gitignored)
 *   - .DS_Store                  macOS cruft
 *
 * It does NOT touch node_modules/ (use `npm install` to rebuild that) nor
 * source files. The downloaded ONNX models live under dist/extension/models/
 * which is already covered by the dist/ removal.
 *
 * Usage:
 *   node scripts/clean.mjs            # clean everything (default)
 *   node scripts/clean.mjs --dry-run  # list what would be removed, delete nothing
 *   node scripts/clean.mjs --keep-models  # remove dist/ but keep downloaded
 *                                          # model weights (dist/extension/models
 *                                          # is re-staged under .models-cache/)
 *
 * Exits 0 even if some paths are already absent; exits 1 only on a real FS
 * error. Prints a summary at the end so a clean build has a clear "before".
 */
import { rmSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const args = new Set(process.argv.slice(2));
const DRY = args.has("--dry-run") || args.has("-n");
const KEEP_MODELS = args.has("--keep-models");

const humanBytes = (n) => {
  if (n >= 1024 ** 3) return `${(n / 1024 ** 3).toFixed(2)} GiB`;
  if (n >= 1024 ** 2) return `${(n / 1024 ** 2).toFixed(1)} MiB`;
  if (n >= 1024) return `${(n / 1024).toFixed(1)} KiB`;
  return `${n} B`;
};

/** Recursive directory size, best-effort (ignores symlink errors). */
function dirSize(p) {
  let total = 0;
  try {
    for (const entry of readdirSync(p)) {
      const full = join(p, entry);
      const st = statSync(full);
      if (st.isDirectory()) total += dirSize(full);
      else total += st.size;
    }
  } catch {
    /* unreadable entry — ignore */
  }
  return total;
}

// ---- paths to remove -------------------------------------------------------

// { path, label } — label used in the summary; path is absolute.
const targets = [];

// Build outputs.
targets.push({ path: join(ROOT, "dist"), label: "dist/ (build output + vendored models)" });
targets.push({ path: join(ROOT, "dist-extension-types"), label: "dist-extension-types/" });

// Model download lock (gitignored; regenerated by scripts/fetch-model.mjs).
targets.push({ path: join(ROOT, "scripts", "model-lock.json"), label: "scripts/model-lock.json" });

// Stray logs + macOS cruft at the repo root.
for (const name of readdirSync(ROOT)) {
  if (name.endsWith(".log") || name === ".DS_Store") {
    const full = join(ROOT, name);
    if (existsSync(full) && statSync(full).isFile()) {
      targets.push({ path: full, label: name });
    }
  }
}

// ---- run -------------------------------------------------------------------

let removedCount = 0;
let removedBytes = 0;
const skipped = [];

if (KEEP_MODELS) {
  // Move dist/extension/models aside before removing dist/, then restore it
  // into a temp cache the next build can reuse. We just leave it in place by
  // deleting everything in dist/ except the models dir.
  const dist = join(ROOT, "dist");
  if (existsSync(dist)) {
    for (const entry of readdirSync(dist)) {
      if (entry === "extension") continue; // handled below
      const full = join(dist, entry);
      targets.push({ path: full, label: `dist/${entry}`, keepModels: true });
    }
    const ext = join(dist, "extension");
    if (existsSync(ext)) {
      for (const entry of readdirSync(ext)) {
        if (entry === "models") continue;
        const full = join(ext, entry);
        targets.push({ path: full, label: `dist/extension/${entry}`, keepModels: true });
      }
    }
  }
  // Filter out the blanket dist/ target so we don't nuke the models.
  for (let i = targets.length - 1; i >= 0; i--) {
    if (targets[i].path === dist) targets.splice(i, 1);
  }
}

for (const t of targets) {
  if (!existsSync(t.path)) {
    skipped.push({ ...t, reason: "absent" });
    continue;
  }
  let size = 0;
  try {
    const st = statSync(t.path);
    size = st.isDirectory() ? dirSize(t.path) : st.size;
  } catch {
    /* size unknown */
  }

  if (DRY) {
    console.log(`  would remove  ${t.label}  ${size ? `(${humanBytes(size)})` : ""}`);
    continue;
  }

  try {
    rmSync(t.path, { recursive: true, force: true });
    console.log(`  removed       ${t.label}  ${size ? `(${humanBytes(size)})` : ""}`);
    removedCount++;
    removedBytes += size;
  } catch (err) {
    console.error(`  ✗ failed      ${t.label}: ${err instanceof Error ? err.message : err}`);
  }
}

if (skipped.length > 0 && !DRY) {
  for (const s of skipped) {
    // Silent for absent paths — they're the normal case. Only mention if
    // there were many, to avoid noise.
  }
}

console.log(
  DRY
    ? `\ndry-run complete: ${targets.length} path(s) would be removed.`
    : `\nclean complete: ${removedCount} path(s) removed` +
      (removedBytes ? `, ${humanBytes(removedBytes)} freed` : "") +
      ".",
);

if (KEEP_MODELS && !DRY) {
  console.log(
    "  (kept dist/extension/models/ — next build reuses cached weights)",
  );
}
